include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.pb.dart'
    - '**/*.pbenum.dart'
    - '**/*.pbjson.dart'
    - '**/*.h.dart'
    - 'lib/gen/*.dart'
    - '**/*.mocks.dart'


linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
