name: catweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_speed_dial: ^6.0.0
  flutter_rating_bar: ^4.0.1
  flutter_linkify: ^5.0.2
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.4
  flutter_sticky_header: ^0.6.3
  flutter_swipe_action_cell: ^3.0.2
  extended_image: ^8.0.1
  cupertino_modal_sheet: ^1.0.0
  bot_toast: ^4.0.2
  scrollable_positioned_list: ^0.3.8
  photo_view:
    git: https://github.com/bluefireteam/photo_view.git

  pull_to_refresh:
    git: https://github.com/miquelbeltran/flutter_pulltorefresh

  # network
  brotli: ^0.5.0
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_db_store: ^5.1.0
  dio_smart_retry: ^5.0.0
  cookie_jar: ^4.0.2
  dio_cookie_manager: ^3.0.0
  dio_http_formatter: ^3.0.0-preview.1

  flutter_inappwebview: ^5.3.2
  webview_cookie_manager: ^2.0.6

  # state
  get: ^4.6.5
  flutter_hooks: ^0.18.4
  event_bus: ^2.0.0

  # database
  drift: ^2.8.0
  shared_preferences: ^2.1.1
  sqlite3_flutter_libs: ^0.5.14
  path_provider: ^2.0.15
  path: any

  # tools
  protobuf: ^2.0.0
  intl: ^0.18.0
  synchronized: ^3.1.0
  uuid: ^3.0.5
  tuple: ^2.0.0
  rxdart: ^0.27.4
  logger: ^1.1.0
  yaml: ^3.1.2
  xml: ^6.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

  # parser
#  catweb_parser:
#    git:
#      url: https://github.com/simonkimi/catweb-parser.git



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  drift_dev: ^2.5.2
  freezed: ^2.3.3
  json_serializable: ^6.6.2
  build_runner: ^2.4.4


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/