name: catweb
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # ui
  flutter_rating_bar: ^4.0.1
  flutter_linkify: ^6.0.0
  flutter_highlight: ^0.7.0
  cupertino_icons: ^1.0.8
  flutter_swipe_action_cell: ^3.1.5
  extended_image: ^9.0.3
  cupertino_modal_sheet: ^1.1.0
  bot_toast: ^4.1.3
  scrollable_positioned_list: ^0.3.8
  photo_view: ^0.15.0

  pull_to_refresh:
    git: https://github.com/miquelbeltran/flutter_pulltorefresh

  # network
  brotli: ^0.6.0
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_db_store: ^5.1.1
  dio_smart_retry: ^6.0.0
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  dio_http_formatter: ^3.2.1

  flutter_inappwebview: ^6.1.5
  webview_cookie_manager: ^2.0.6

  # state
  flutter_hooks: ^0.20.5
  get_it: ^8.0.0
  provider: ^6.1.2


  # database
  drift: ^2.21.0
  shared_preferences: ^2.3.2
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # tools
  intl: ^0.19.0
  synchronized: ^3.3.0+3
  uuid: ^4.5.1
  rxdart: ^0.28.0
  logger: ^2.4.0
  yaml: ^3.1.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  collection: ^1.18.0

  # parser
  # catweb_parser:
  #   path: ../catweb_parser_go



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.21.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  custom_lint: ^0.6.8



flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/